version: '2'
services:
  mongodbhost:
    image: mongo:3.3.5
    ports:
      - "27017:27017"

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    links:
      - mongodbhost

  tcell_web:
    build: .
    command: tcell_agent run python app.py
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    links:
      - mongodbhost

  tcell_local_web:
    build: .
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run python app.py"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "8002:8002"
    links:
      - mongodbhost

  #uwsgi --socket 0.0.0.0:8002 --protocol=http -w wsgi
  tcell_uwsgi_local_web:
    build: .
    command: sh -c "pip install -e /tcellagent_src && tcell_agent run uwsgi --socket 0.0.0.0:8002 --protocol=http --enable-threads -w wsgi"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "8002:8002"
    links:
      - mongodbhost

  tcell_gunicorn_local_web:
    build: .
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run gunicorn --bind 0.0.0.0:8002 wsgi"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "8002:8002"
    links:
      - mongodbhost

